module.exports = [
    {
        lostStatus: "true",
        name: "Henry",
        species: "Cat",
        gender: "Male",
        size: "Small",
        color: "Orange, White",
        age: "Adult",
        breed: "Tabby",
        temperament: "Friendly",
        comments: "Henry is friendly and sweet!",
        dateLostOrFound: "2019-12-04",
        chipId: "985A23A456B7981",
        additionalLostFoundInfo: "Lost near his home.",
        latitude: "39.758194",
        longitude: "-104.980886",
        pictureUrl: "https://www.thehappycatsite.com/wp-content/uploads/2017/10/Orange-Tabby-Cat-Fascinating-Facts-About-Orange-Cats-HC-long.jpg"
    },
    {
        lostStatus: "true",
        name: "Fluffy",
        species: "Cat",
        gender: "Male",
        size: "Small",
        color: "White",
        age: "Kitten",
        breed: "Tabby",
        temperament: "Nervous, friendly",
        comments: "Fluffy is nervous and timid, but once she warms up she is very friendly and sweet!",
        dateLostOrFound: "2019-11-04",
        chipId: "977B23A477B7990",
        additionalLostFoundInfo: "Fluffy is an indoor/outdoor who usually comes home in the evenings but hasn't returned since November 4, 2019.",
        latitude: "39.764149",
        longitude: "-105.016586",
        pictureUrl: "https://www.publicdomainpictures.net/pictures/10000/nahled/1-1276781631XYvY.jpg"
    },
    {
        lostStatus: "true",
        name: "Michael",
        species: "Cat",
        gender: "Female",
        size: "Small",
        color: "White",
        age: "Adult",
        breed: "Siamese",
        temperament: "Timid",
        comments: "Michael is timid but a sweet cat.",
        dateLostOrFound: "2019-11-15",
        chipId: "782C23A456B7091",
        additionalLostFoundInfo: "Michael got out when the door was left open :(",
        latitude: "39.720662",
        longitude: "-105.042342",
        pictureUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Siamese_cat_sitting.jpg"
    },
    {
        lostStatus: "true",
        name: "Jacky",
        species: "Dog",
        gender: "Female",
        size: "Medium",
        color: "Brown",
        age: "Adult",
        breed: "Pitbull Terrier",
        temperament: "Friendly",
        comments: "Jacky is very friendly but is sometimes shy around new people.",
        dateLostOrFound: "2019-11-07",
        chipId: "782C23B256B6561",
        additionalLostFoundInfo: "Jacky got out through a hole in the fence.",
        latitude: "39.687205",
        longitude: "-105.063836",
        pictureUrl: "https://www.k9web.com/wp-content/uploads/2019/05/Red-Nose-Pitbull-13.jpg"
    },
    {
        lostStatus: "true",
        name: "Gus",
        species: "Dog",
        gender: "Male",
        size: "Small",
        color: "White, Brown",
        age: "Adult",
        breed: "Bulldog",
        temperament: "Sweet",
        comments: "Gus is very friendly and sweet!",
        dateLostOrFound: "2019-11-07",
        chipId: "509D23A456AB091",
        additionalLostFoundInfo: "Gus got lost during a storm.",
        latitude: "39.643002",
        longitude: "-104.987410",
        pictureUrl: "https://image.shutterstock.com/image-photo/british-bulldog-puppy-looking-isolated-260nw-1446556445.jpg"
    },
    {
        lostStatus: "true",
        name: "Pip",
        species: "Dog",
        gender: "Male",
        size: "Small",
        color: "White",
        age: "Puppy",
        breed: "Chihuahua",
        temperament: "Nervous",
        comments: "Pip is very timid and is easily frightened.",
        dateLostOrFound: "2019-11-07",
        chipId: "287C23A455T9891",
        additionalLostFoundInfo: "Pip escaped from our yard when the gate wasn't locked all the way.",
        latitude: "39.841284",
        longitude: "-105.057491",
        pictureUrl: "https://photos.puppyspot.com/breeds/219/card/500000282_medium.jpg"
    },
]